import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { IArtObject, IArtState } from '../../model/IArtObject';
import { fetchArtObjectById } from './artAPI';

export const initialState: IArtState = {
  entities: undefined,
};

export const fetchArtById = createAsyncThunk(
  'search/fetchArt',
  async (id: number): Promise<IArtObject> => {
    const result = await fetchArtObjectById(id);
    return await result.json();
  }
);

export const artSlice = createSlice({
  name: 'arts',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchArtById.pending, (state, { meta, payload }) => {
        console.log('meta', meta, payload);

        state.entities = {
          ...state.entities,
          [meta.arg]: {
            status: 'loading',
            error: '',
            data: undefined,
          },
        };
      })
      .addCase(fetchArtById.fulfilled, (state, { meta, payload }) => {
        // todo

        state.entities = {
          ...state.entities,
          [meta.arg]: {
            status: 'idle',
            error: '',
            data: payload,
          },
        };
      })
      .addCase(fetchArtById.rejected, (state, { meta }) => {
        state.entities = {
          ...state.entities,
          [meta.arg]: {
            status: 'failed',
            error: 'Something went wrong!!!!',
            date: undefined,
          },
        };
      });
  },
});

export default artSlice.reducer;
