import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState } from 'app/store';
import { mapKeys, reduce } from 'lodash';
import { IDepartmentResult, IDepartmentSate } from '../../model/IDepartment';
import { fetchAllDepartments } from './departmentAPI';

export const initialState: IDepartmentSate = {
  status: 'idle',
  error: '',
  entities: undefined,
};

export const fetchDepartments = createAsyncThunk(
  'search/fetchDepartments',
  async (): Promise<IDepartmentResult> => {
    const result = await fetchAllDepartments();
    return await result.json();
  }
);

export const departmentSlice = createSlice({
  name: 'department',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchDepartments.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchDepartments.fulfilled, (state, { payload }) => {
        state.status = 'idle';
        state.error = '';
        state.entities = mapKeys(payload.departments, (x) => x.departmentId);
      })
      .addCase(fetchDepartments.rejected, (state) => {
        state.status = 'failed';
        state.error = 'Something went wrong...... TODO';
        state.entities = undefined;
      });
  },
});

export const getDepartments = (state: RootState) => state.department.entities;

export default departmentSlice.reducer;
